
stages:
  - validate


# Job to deploy my Infrastructure using terraform to AWS.
create aws infrastructure according to terraform:
    stage: validate
    image:
      name: hashicorp/terraform:1.3.6
      entrypoint: [""]
    script:
      - terraform -version
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -input=false