
stages:
  - validate


# Job to deploy my Infrastructure using terraform to AWS.
create aws infrastructure according to terraform:
    stage: validate
    image: hashicorp/terraform:1.3.6
    script:
      - terraform --version